aplicacion V2/hotelapp/comentarios/urls.py
from django.urls import path
from .views import get_Negativos
from .views import hotel_chart
from .views import get_Palabras

app_name = 'csvs'

urlpatterns = [
    path('', get_Negativos, name= 'upload-view'),
    path('chart', hotel_chart, name= 'chart-view'),
    path('negativos', get_Palabras, name= 'negs-view'),

]

aplicacion V2/hotelapp/csvs/urls.py
from django.urls import path
from .views import upload_file_view

app_name = 'comentarios'

urlpatterns = [
    path('', upload_file_view, name= 'upload-view'),
]

aplicacion V2/hotelapp/hotelapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('carga/', include('csvs.urls', namespace='csvs')),
    path('negativos/', include('comentarios.urls', namespace='comentarios')),
    path('solos/', include('singles.urls', namespace='singles')),
    path('', include('paginaPrin.urls', namespace='paginaPrin')),
    path('predict/', include('predict.urls', namespace='predict')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicacion V2/hotelapp/paginaPrin/urls.py
from django.urls import path
from . import views

app_name = 'paginaPrin'

urlpatterns = [
    path('', views.index, name='index'),
]

aplicacion V2/hotelapp/comentarios/models.py
from django.db import models

# Create your models here.
class Comentario(models.Model):
    idd = models.PositiveSmallIntegerField(default=5, primary_key=True)
    title = models.TextField(max_length=200)
    rating = models.PositiveSmallIntegerField(default=5)
    texto = models.TextField()
    location = models.TextField(max_length=200)
    hotel = models.TextField(max_length=200)
    negativo = models.BooleanField(default=False)


    
    def __str__(self):
        return '%s' % (self.idd, self.title, self.rating, self.texto, self.location, self.hotel, self.negativo)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

aplicacion V2/hotelapp/comentarios/views.py
from django.shortcuts import render
from .models import Comentario
from django.db.models import Count

def hotel_chart(request):
    # Obtener la cantidad de hoteles con negativo=True y negativo=False
    negativos = Comentario.objects.filter(negativo=True).count()
    no_negativos = Comentario.objects.filter(negativo=False).count()
    
    # Crear los datos para el gráfico
    labels = ['Negativos', 'No negativos']
    values = [negativos, no_negativos]
    
    # Crear un diccionario con los datos del gráfico para pasar al template
    context = {'labels': labels, 'values': values}
    
    return render(request, 'hotel_chart.html', context)

# Create your views here.
def get_Negativos(request):
    objetos_negativos = Comentario.objects.filter(negativo=True)
    context = {'objetos': objetos_negativos}
    return render(request, 'lavista.html', context)

def get_Palabras(request):
    comentarios = Comentario.objects.all()
    palabras = ['asin', 'asco', 'ausencia', 'ausenci', 'car', 'carisim', 'cucarach', 'cucaracha', 'corresponder', 'cuatro', 'deficient', 'decepcion', 'des', 'desear', 'decente', 'lamentable', 'educacion', 'esperar', 'horror', 'horrible', 'horribl', 'junior', 'jabon', 'lament', 'muell', 'pesim', 'pesimo', 'pesimar', 'pasable', 'pasabl', 'pared', 'rot', 'sucio', 'suci', 'sabana', 'saban', 'teni', 'vending', 'diecioch', 'dieciocho', 'cristobal', '360o', 'doscientos']
    negWords = []
    for comentario in comentarios :
        for palabra in comentario.texto.split():
            if palabra in palabras:
                negWords.append(palabra)

    context = {'palabras': negWords}
    return render(request, 'laspalabras.html', context)

aplicacion V2/hotelapp/comentarios/templates/hotel_chart.html
{% extends 'base.html' %}

{% block content %}

<nav>
    <ul>
      <li><a href="{% url 'csvs:chart-view' %}">Graficos</a></li>
      <li><a href="{% url 'csvs:negs-view' %}">Palabras negativas</a></li>
      <li><a href="{% url 'csvs:upload-view' %}">Reseñas negativas</a></li>
      <li><a href="{% url 'paginaPrin:index' %}">Pagina Principal</a></li>
    </ul>
  </nav>

    <div class="container">
        <h1>Gráfico de hoteles con comentarios negativos</h1>
        <canvas id="hotelChart"></canvas>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        var ctx = document.getElementById('hotelChart').getContext('2d');
        var chart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: {{ labels|safe }},
                datasets: [{
                    backgroundColor: ['#dc3545', '#28a745'],
                    data: {{ values|safe }}
                }]
            }
        });
    </script>
{% endblock %}

aplicacion V2/hotelapp/comentarios/templates/laspalabras.html
{% extends 'base.html' %}

{% block content %}

<nav>
  <ul>
    <li><a href="{% url 'csvs:chart-view' %}">Graficos</a></li>
    <li><a href="{% url 'csvs:negs-view' %}">Palabras negativas</a></li>
    <li><a href="{% url 'csvs:upload-view' %}">Reseñas negativas</a></li>
    <li><a href="{% url 'paginaPrin:index' %}">Pagina Principal</a></li>
  </ul>
</nav>

<h1>PALABRAS MAS NEGATIVAS EN TUS COMENTARIOS</h1>
<style>
    .form-group {
      margin-bottom: 20px;
    }
    input[type="text"] {
      border-radius: 0;
      border: 2px solid #ccc;
      box-shadow: none;
      height: 50px;
      font-size: 18px;
      padding: 10px;
    }
  </style>
  
<div class="container">
  <div class="row">
    {% for palabra in palabras %}

    <div class="col-sm-4">
      <div class="form-group">
        <fieldset style="border: 2px solid #ccc; padding: 10px; border-radius: 10px;">
            <legend style="font-size: 1.2rem; font-weight: bold; color: #333; background-color: #f0f0f0; padding: 5px; border-radius: 5px;">Palabra</legend>
            <label style="font-size: 1.2rem; font-weight: bold; color: #333;">{{ palabra }}</label>
          </fieldset>

      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

aplicacion V2/hotelapp/comentarios/templates/lavista.html
{% extends 'base.html' %}

{% block title %}
main page
{% endblock title %}




{% block content %}

<nav>
  <ul>
    <li><a href="{% url 'csvs:chart-view' %}">Graficos</a></li>
    <li><a href="{% url 'csvs:negs-view' %}">Palabras negativas</a></li>
    <li><a href="{% url 'csvs:upload-view' %}">Reseñas negativas</a></li>
    <li><a href="{% url 'paginaPrin:index' %}">Pagina Principal</a></li>
  </ul>
</nav>

<div class="container">
  <h1>Comentarios negativos</h1>
  <canvas id="hotelChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  var ctx = document.getElementById('hotelChart').getContext('2d');
  var chart = new Chart(ctx, {
      type: 'pie',
      data: {
          labels: {{ labels|safe }},
          datasets: [{
              backgroundColor: ['#dc3545', '#28a745'],
              data: {{ values|safe }}
          }]
      },
      options: {
          responsive: true,
          maintainAspectRatio: false
      }
  });
</script>
<table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Rating</th>
        <th>Texto</th>
        <th>Location</th>
        <th>Hotel</th>
      </tr>
    </thead>
    <tbody>
      {% for objeto in objetos %}
        <tr>
          <td>{{ objeto.idd }}</td>
          <td>{{ objeto.title }}</td>
          <td>{{ objeto.rating }}</td>
          <td>{{ objeto.texto }}</td>
          <td>{{ objeto.location }}</td>
          <td>{{ objeto.hotel }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}