aplicacion V2/hotelapp/csvs/urls.py
from django.urls import path
from .views import upload_file_view

app_name = 'comentarios'

urlpatterns = [
    path('', upload_file_view, name= 'upload-view'),
]

aplicacion V2/hotelapp/hotelapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('carga/', include('csvs.urls', namespace='csvs')),
    path('negativos/', include('comentarios.urls', namespace='comentarios')),
    path('solos/', include('singles.urls', namespace='singles')),
    path('', include('paginaPrin.urls', namespace='paginaPrin')),
    path('predict/', include('predict.urls', namespace='predict')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicacion V2/hotelapp/paginaPrin/urls.py
from django.urls import path
from . import views

app_name = 'paginaPrin'

urlpatterns = [
    path('', views.index, name='index'),
]

aplicacion V2/hotelapp/predict/urls.py
from django.urls import path
from . import views

app_name = 'predict'

urlpatterns = [
    path('', views.home, name='home'),
]

aplicacion V2/hotelapp/paginaPrin/models.py
from django.db import models

# Create your models here.

aplicacion V2/hotelapp/paginaPrin/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

aplicacion V2/hotelapp/paginaPrin/templates/index.html
<!DOCTYPE html>
<html>
<head>
  <title>Mi sitio web</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Cargar CSS externo -->
  <style>
    {% include "style.css" %}
  </style>
</head>
<body>
  <!-- Encabezado -->
  <header>
    <nav>
      <ul>
        <li><a href="{% url 'paginaPrin:index' %}">Inicio</a></li>
        <li><a href="{% url 'csvs:upload-view' %}">Negativos</a></li>
        <li><a href="{% url 'comentarios:upload-view' %}">Carga de datos</a></li>
        <li><a href="{% url 'predict:home' %}">Solos</a></li>
      </ul>
    </nav>
  </header>

  <!-- Contenido principal -->
  <main>
    <section class="hero">
      <h1>Proyecto BI 1</h1>
      <p>Selecciona una de las siguientes opciones:</p>
      <ul>
        <li>
          <a href="{% url 'csvs:upload-view' %}">
            <i class="fa fa-camera"></i>
            <h2>Comentarios negativos</h2>
          </a>
        </li>
        <li>
          <a href="{% url 'comentarios:upload-view' %}">
            <i class="fa fa-music"></i>
            <h2>Carga de datos</h2>
          </a>
        </li>
        <li>
          <a href="{% url 'predict:home' %}">
            <i class="fa fa-book"></i>
            <h2>comentarios solos</h2>
          </a>
        </li>
      </ul>
    </section>
  </main>

  <!-- Pie de página -->
  <footer>
    <p>Proy BI 1</p>
  </footer>

</body>
</html>